version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.9-apache-node-browsers
    steps:
    - checkout
    
workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
